// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HostPingResult is the outcome of a TCP reachability check.
 */
export class HostPingResult {
    "id": string;
    "reachable": boolean;
    "latencyMs": number;

    /** Creates a new HostPingResult instance. */
    constructor($$source: Partial<HostPingResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("reachable" in $$source)) {
            this["reachable"] = false;
        }
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostPingResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HostPingResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostPingResult($$parsedSource as Partial<HostPingResult>);
    }
}

/**
 * HostPingTarget identifies a host to probe.
 */
export class HostPingTarget {
    "id": string;
    "host": string;
    "port": number;
    "local": boolean;

    /** Creates a new HostPingTarget instance. */
    constructor($$source: Partial<HostPingTarget> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("local" in $$source)) {
            this["local"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostPingTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): HostPingTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostPingTarget($$parsedSource as Partial<HostPingTarget>);
    }
}
