// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckPrivateKeyNeedsPassphrase(privateKey: string): $CancellablePromise<boolean> {
    return $Call.ByID(2238678926, privateKey);
}

export function Connect(config: $models.SSHConnectionConfig | null): $CancellablePromise<void> {
    return $Call.ByID(662660765, config);
}

/**
 * ConnectForwardOnly opens an SSH client without a shell, for port forwarding only.
 */
export function ConnectForwardOnly(config: $models.SSHConnectionConfig | null): $CancellablePromise<void> {
    return $Call.ByID(1535207060, config);
}

export function Disconnect(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2124563103, sessionID);
}

/**
 * Input writes data to SSH stdin
 */
export function Input(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(187872847, sessionID, data);
}

export function ListPortForwards(sessionID: string): $CancellablePromise<$models.PortForward[]> {
    return $Call.ByID(2962886936, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Resize(sessionID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(639676773, sessionID, rows, cols);
}

export function SftpChmod(sessionID: string, remotePath: string, mode: number): $CancellablePromise<void> {
    return $Call.ByID(911228333, sessionID, remotePath, mode);
}

export function SftpDownload(sessionID: string, remotePath: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(2112044164, sessionID, remotePath, localPath);
}

export function SftpList(sessionID: string, remotePath: string): $CancellablePromise<$models.SftpEntry[]> {
    return $Call.ByID(417381892, sessionID, remotePath).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SftpMkdir(sessionID: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1399921231, sessionID, remotePath);
}

/**
 * SftpPrepareEdit downloads a remote file to a temp path for external editing.
 */
export function SftpPrepareEdit(sessionID: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(1235543291, sessionID, remotePath);
}

export function SftpRemove(sessionID: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(984273452, sessionID, remotePath);
}

export function SftpRename(sessionID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(569627294, sessionID, oldPath, newPath);
}

export function SftpUpload(sessionID: string, localPath: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(4185042813, sessionID, localPath, remotePath);
}

export function StartLocalForward(sessionID: string, id: string, localHost: string, localPort: number, remoteHost: string, remotePort: number): $CancellablePromise<void> {
    return $Call.ByID(3842866583, sessionID, id, localHost, localPort, remoteHost, remotePort);
}

export function StartRemoteForward(sessionID: string, id: string, localHost: string, localPort: number, remoteHost: string, remotePort: number): $CancellablePromise<void> {
    return $Call.ByID(1470280926, sessionID, id, localHost, localPort, remoteHost, remotePort);
}

export function StopPortForward(id: string): $CancellablePromise<void> {
    return $Call.ByID(302194887, id);
}

// Private type creation functions
const $$createType0 = $models.PortForward.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SftpEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
