// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExportResult is returned after a successful export.
 */
export class ExportResult {
    "path": string;
    "cancelled": boolean;

    /** Creates a new ExportResult instance. */
    constructor($$source: Partial<ExportResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResult($$parsedSource as Partial<ExportResult>);
    }
}

/**
 * ImportResult counts items added during an import.
 */
export class ImportResult {
    "hostsImported": number;
    "keysImported": number;
    "identitiesImported": number;
    "snippetsImported": number;
    "forwardsImported": number;
    "groupsImported": number;
    "tabGroupsImported": number;
    "knownHostsMerged": number;
    "cancelled": boolean;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("hostsImported" in $$source)) {
            this["hostsImported"] = 0;
        }
        if (!("keysImported" in $$source)) {
            this["keysImported"] = 0;
        }
        if (!("identitiesImported" in $$source)) {
            this["identitiesImported"] = 0;
        }
        if (!("snippetsImported" in $$source)) {
            this["snippetsImported"] = 0;
        }
        if (!("forwardsImported" in $$source)) {
            this["forwardsImported"] = 0;
        }
        if (!("groupsImported" in $$source)) {
            this["groupsImported"] = 0;
        }
        if (!("tabGroupsImported" in $$source)) {
            this["tabGroupsImported"] = 0;
        }
        if (!("knownHostsMerged" in $$source)) {
            this["knownHostsMerged"] = 0;
        }
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}
