// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DefaultKnownHostsPath(): $CancellablePromise<string> {
    return $Call.ByID(3118068160);
}

export function DefaultSSHConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(2425710548);
}

export function ExportVault(encrypted: boolean, password: string): $CancellablePromise<$models.ExportResult> {
    return $Call.ByID(768732674, encrypted, password).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportSSHConfig(configPath: string, mergeKnownHosts: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(251977379, configPath, mergeKnownHosts).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportSSHConfigWithDialog(mergeKnownHosts: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(868707431, mergeKnownHosts).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportVault(password: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(868543295, password).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExportResult.createFrom;
const $$createType1 = $models.ImportResult.createFrom;
