// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    "language": string;
    "terminalFontFamily": string;
    "terminalFontSize": number;
    "showLocalhostHost": boolean;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("terminalFontFamily" in $$source)) {
            this["terminalFontFamily"] = "";
        }
        if (!("terminalFontSize" in $$source)) {
            this["terminalFontSize"] = 0;
        }
        if (!("showLocalhostHost" in $$source)) {
            this["showLocalhostHost"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * TerminalFontFace describes how the frontend should load the terminal font.
 */
export class TerminalFontFace {
    /**
     * Family is the CSS font-family value for xterm (may be a @font-face alias).
     */
    "family": string;

    /**
     * CSS is an optional @font-face rule (data URL) when a system file was resolved.
     */
    "css"?: string;

    /** Creates a new TerminalFontFace instance. */
    constructor($$source: Partial<TerminalFontFace> = {}) {
        if (!("family" in $$source)) {
            this["family"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalFontFace instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalFontFace {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalFontFace($$parsedSource as Partial<TerminalFontFace>);
    }
}
