// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SavedTileNode mirrors the frontend tab-group tile JSON shape.
 */
export class SavedTileNode {
    "kind": string;
    "hostIndex"?: number;
    "direction"?: string;
    "first"?: SavedTileNode | null;
    "second"?: SavedTileNode | null;

    /** Creates a new SavedTileNode instance. */
    constructor($$source: Partial<SavedTileNode> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedTileNode instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedTileNode {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("first" in $$parsedSource) {
            $$parsedSource["first"] = $$createField3_0($$parsedSource["first"]);
        }
        if ("second" in $$parsedSource) {
            $$parsedSource["second"] = $$createField4_0($$parsedSource["second"]);
        }
        return new SavedTileNode($$parsedSource as Partial<SavedTileNode>);
    }
}

export class Snapshot {
    "version": number;
    "tabs": Tab[];
    "activeTabIndex": number;
    "activeHostId": string;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("tabs" in $$source)) {
            this["tabs"] = [];
        }
        if (!("activeTabIndex" in $$source)) {
            this["activeTabIndex"] = 0;
        }
        if (!("activeHostId" in $$source)) {
            this["activeHostId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField1_0($$parsedSource["tabs"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

export class Tab {
    "hostIds": string[];
    "tileLayout"?: SavedTileNode | null;
    "tabGroupId"?: string;

    /** Creates a new Tab instance. */
    constructor($$source: Partial<Tab> = {}) {
        if (!("hostIds" in $$source)) {
            this["hostIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tab instance from a string or object.
     */
    static createFrom($$source: any = {}): Tab {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hostIds" in $$parsedSource) {
            $$parsedSource["hostIds"] = $$createField0_0($$parsedSource["hostIds"]);
        }
        if ("tileLayout" in $$parsedSource) {
            $$parsedSource["tileLayout"] = $$createField1_0($$parsedSource["tileLayout"]);
        }
        return new Tab($$parsedSource as Partial<Tab>);
    }
}

// Private type creation functions
const $$createType0 = SavedTileNode.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Tab.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
