// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearSnapshot(): $CancellablePromise<void> {
    return $Call.ByID(134040684);
}

export function GetSnapshot(): $CancellablePromise<[$models.Snapshot, boolean]> {
    return $Call.ByID(2017512737).then(($result: any) => {
        $result[0] = $$createType0($result[0]);
        return $result;
    });
}

export function HasSnapshot(): $CancellablePromise<boolean> {
    return $Call.ByID(707002333);
}

export function SaveSnapshot(snapshot: $models.Snapshot): $CancellablePromise<void> {
    return $Call.ByID(3392215694, snapshot);
}

// Private type creation functions
const $$createType0 = $models.Snapshot.createFrom;
