// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Entry {
    "id": string;
    "command": string;
    "hostId": string;
    "hostLabel": string;
    "usedAt": string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("hostId" in $$source)) {
            this["hostId"] = "";
        }
        if (!("hostLabel" in $$source)) {
            this["hostLabel"] = "";
        }
        if (!("usedAt" in $$source)) {
            this["usedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}
