// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Append(hostID: string, hostLabel: string, command: string): $CancellablePromise<void> {
    return $Call.ByID(1496957804, hostID, hostLabel, command);
}

export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(1558699249);
}

export function ClearHost(hostID: string): $CancellablePromise<void> {
    return $Call.ByID(3174659467, hostID);
}

export function Search(query: string, scope: string, hostID: string, limit: number): $CancellablePromise<$models.Entry[]> {
    return $Call.ByID(3115579168, query, scope, hostID, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
