// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RunningContainer describes a local container that is currently running.
 */
export class RunningContainer {
    "id": string;
    "name": string;
    "image": string;
    "status": string;
    "state": string;
    "runtime": string;

    /** Creates a new RunningContainer instance. */
    constructor($$source: Partial<RunningContainer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("runtime" in $$source)) {
            this["runtime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunningContainer instance from a string or object.
     */
    static createFrom($$source: any = {}): RunningContainer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunningContainer($$parsedSource as Partial<RunningContainer>);
    }
}
