// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DetectRuntime returns the first available container CLI on PATH.
 */
export function DetectRuntime(): $CancellablePromise<string> {
    return $Call.ByID(460421902);
}

/**
 * ListRunning returns running containers for the given runtime (empty = auto-detect).
 */
export function ListRunning(runtime: string): $CancellablePromise<$models.RunningContainer[]> {
    return $Call.ByID(2932910244, runtime).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RunningContainer.createFrom;
const $$createType1 = $Create.Array($$createType0);
