// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3737150046, id);
}

export function GetAll(): $CancellablePromise<$models.HostGroup[]> {
    return $Call.ByID(2989409854).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Save(group: $models.HostGroup): $CancellablePromise<string> {
    return $Call.ByID(3839439276, group);
}

// Private type creation functions
const $$createType0 = $models.HostGroup.createFrom;
const $$createType1 = $Create.Array($$createType0);
