// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(123785957, id);
}

export function GetAll(): $CancellablePromise<$models.SavedIdentity[]> {
    return $Call.ByID(3555447221).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Save(identity: $models.SavedIdentity): $CancellablePromise<string> {
    return $Call.ByID(1046004455, identity);
}

// Private type creation functions
const $$createType0 = $models.SavedIdentity.createFrom;
const $$createType1 = $Create.Array($$createType0);
