// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2018517502, id);
}

export function DerivePublicKey(privateKey: string): $CancellablePromise<string> {
    return $Call.ByID(20729994, privateKey);
}

export function GenerateKeyPair(req: $models.GenerateSSHKeyRequest): $CancellablePromise<$models.GeneratedSSHKey> {
    return $Call.ByID(3247754137, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAll(): $CancellablePromise<$models.SavedKey[]> {
    return $Call.ByID(2217667998).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Save(key: $models.SavedKey): $CancellablePromise<string> {
    return $Call.ByID(2642404940, key);
}

// Private type creation functions
const $$createType0 = $models.GeneratedSSHKey.createFrom;
const $$createType1 = $models.SavedKey.createFrom;
const $$createType2 = $Create.Array($$createType1);
