// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GenerateSSHKeyRequest {
    "algorithm": string;
    "comment": string;

    /** Creates a new GenerateSSHKeyRequest instance. */
    constructor($$source: Partial<GenerateSSHKeyRequest> = {}) {
        if (!("algorithm" in $$source)) {
            this["algorithm"] = "";
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateSSHKeyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateSSHKeyRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateSSHKeyRequest($$parsedSource as Partial<GenerateSSHKeyRequest>);
    }
}

export class GeneratedSSHKey {
    "algorithm": string;
    "privateKey": string;
    "publicKey": string;
    "fingerprint": string;

    /** Creates a new GeneratedSSHKey instance. */
    constructor($$source: Partial<GeneratedSSHKey> = {}) {
        if (!("algorithm" in $$source)) {
            this["algorithm"] = "";
        }
        if (!("privateKey" in $$source)) {
            this["privateKey"] = "";
        }
        if (!("publicKey" in $$source)) {
            this["publicKey"] = "";
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneratedSSHKey instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneratedSSHKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneratedSSHKey($$parsedSource as Partial<GeneratedSSHKey>);
    }
}

export class Host {
    "id": string;
    "type": ItemType;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "password"?: string;
    "keyId"?: string;
    "identityId"?: string;
    "userpassIdentityIds"?: string[];
    "groupId"?: string;
    "relayHostId"?: string;
    "icon"?: string;
    "color"?: string;
    "startupCommand"?: string;
    "environment"?: { [_ in string]?: string };
    "terminalFontFamily"?: string;
    "terminalFontSize"?: number;
    "notes"?: string;
    "tags"?: string[];

    /** Creates a new Host instance. */
    constructor($$source: Partial<Host> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     */
    static createFrom($$source: any = {}): Host {
        const $$createField9_0 = $$createType0;
        const $$createField15_0 = $$createType1;
        const $$createField19_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("userpassIdentityIds" in $$parsedSource) {
            $$parsedSource["userpassIdentityIds"] = $$createField9_0($$parsedSource["userpassIdentityIds"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField15_0($$parsedSource["environment"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField19_0($$parsedSource["tags"]);
        }
        return new Host($$parsedSource as Partial<Host>);
    }
}

export class HostGroup {
    "id": string;
    "type": ItemType;
    "name": string;
    "parentId"?: string;
    "sortOrder"?: number;
    "icon"?: string;
    "color"?: string;

    /** Creates a new HostGroup instance. */
    constructor($$source: Partial<HostGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): HostGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostGroup($$parsedSource as Partial<HostGroup>);
    }
}

export enum ItemType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeHost = "host",
    TypeKey = "key",
    TypeGroup = "group",
    TypeIdentity = "identity",
    TypeSnippet = "snippet",
    TypeForward = "forward",
    TypeTabGroup = "tabGroup",
};

export class SavedForward {
    "id": string;
    "type": ItemType;
    "name": string;
    "hostId": string;

    /**
     * "local" (default) or "remote"
     */
    "mode": string;
    "localHost": string;
    "localPort": number;
    "remoteHost": string;
    "remotePort": number;

    /** Creates a new SavedForward instance. */
    constructor($$source: Partial<SavedForward> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hostId" in $$source)) {
            this["hostId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("localHost" in $$source)) {
            this["localHost"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("remoteHost" in $$source)) {
            this["remoteHost"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedForward instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedForward {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedForward($$parsedSource as Partial<SavedForward>);
    }
}

export class SavedIdentity {
    "id": string;
    "type": ItemType;
    "name": string;
    "username": string;
    "password": string;

    /** Creates a new SavedIdentity instance. */
    constructor($$source: Partial<SavedIdentity> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedIdentity instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedIdentity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedIdentity($$parsedSource as Partial<SavedIdentity>);
    }
}

export class SavedKey {
    "id": string;
    "type": ItemType;
    "name": string;
    "privateKey": string;
    "publicKey"?: string;

    /** Creates a new SavedKey instance. */
    constructor($$source: Partial<SavedKey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("privateKey" in $$source)) {
            this["privateKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedKey instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedKey($$parsedSource as Partial<SavedKey>);
    }
}

export class SavedSnippet {
    "id": string;
    "type": ItemType;
    "name": string;
    "content": string;

    /** Creates a new SavedSnippet instance. */
    constructor($$source: Partial<SavedSnippet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedSnippet instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedSnippet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedSnippet($$parsedSource as Partial<SavedSnippet>);
    }
}

export class TabGroup {
    "id": string;
    "type": ItemType;
    "name": string;
    "hostIds": string[];
    "icon"?: string;
    "color"?: string;
    "sortOrder"?: number;
    "tileLayout"?: TabTileLayoutNode | null;

    /** Creates a new TabGroup instance. */
    constructor($$source: Partial<TabGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hostIds" in $$source)) {
            this["hostIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): TabGroup {
        const $$createField3_0 = $$createType0;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hostIds" in $$parsedSource) {
            $$parsedSource["hostIds"] = $$createField3_0($$parsedSource["hostIds"]);
        }
        if ("tileLayout" in $$parsedSource) {
            $$parsedSource["tileLayout"] = $$createField7_0($$parsedSource["tileLayout"]);
        }
        return new TabGroup($$parsedSource as Partial<TabGroup>);
    }
}

/**
 * TabGroup is a saved multi-host workspace shown in the sidebar.
 * HostIDs holds ordered host references; the same host ID may appear more than once.
 * TileLayout stores the split-tree positions of hosts by index into HostIDs.
 */
export class TabTileLayoutNode {
    "kind": string;
    "hostIndex"?: number;
    "direction"?: string;
    "first"?: TabTileLayoutNode | null;
    "second"?: TabTileLayoutNode | null;

    /** Creates a new TabTileLayoutNode instance. */
    constructor($$source: Partial<TabTileLayoutNode> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabTileLayoutNode instance from a string or object.
     */
    static createFrom($$source: any = {}): TabTileLayoutNode {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("first" in $$parsedSource) {
            $$parsedSource["first"] = $$createField3_0($$parsedSource["first"]);
        }
        if ("second" in $$parsedSource) {
            $$parsedSource["second"] = $$createField4_0($$parsedSource["second"]);
        }
        return new TabTileLayoutNode($$parsedSource as Partial<TabTileLayoutNode>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = TabTileLayoutNode.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
