// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Host {
    "id": string;
    "type": ItemType;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "password"?: string;
    "keyId"?: string;
    "identityId"?: string;
    "userpassIdentityIds"?: string[];
    "groupId"?: string;
    "icon"?: string;
    "color"?: string;

    /** Creates a new Host instance. */
    constructor($$source: Partial<Host> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     */
    static createFrom($$source: any = {}): Host {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("userpassIdentityIds" in $$parsedSource) {
            $$parsedSource["userpassIdentityIds"] = $$createField9_0($$parsedSource["userpassIdentityIds"]);
        }
        return new Host($$parsedSource as Partial<Host>);
    }
}

export class HostGroup {
    "id": string;
    "type": ItemType;
    "name": string;
    "parentId"?: string;
    "sortOrder"?: number;
    "icon"?: string;
    "color"?: string;

    /** Creates a new HostGroup instance. */
    constructor($$source: Partial<HostGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): HostGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostGroup($$parsedSource as Partial<HostGroup>);
    }
}

export enum ItemType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeHost = "host",
    TypeKey = "key",
    TypeGroup = "group",
    TypeIdentity = "identity",
};

export class SavedIdentity {
    "id": string;
    "type": ItemType;
    "name": string;
    "username": string;
    "password": string;

    /** Creates a new SavedIdentity instance. */
    constructor($$source: Partial<SavedIdentity> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedIdentity instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedIdentity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedIdentity($$parsedSource as Partial<SavedIdentity>);
    }
}

export class SavedKey {
    "id": string;
    "type": ItemType;
    "name": string;
    "privateKey": string;

    /** Creates a new SavedKey instance. */
    constructor($$source: Partial<SavedKey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("privateKey" in $$source)) {
            this["privateKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedKey instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedKey($$parsedSource as Partial<SavedKey>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
