// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GenerateSSHKeyRequest {
    "algorithm": string;
    "comment": string;

    /** Creates a new GenerateSSHKeyRequest instance. */
    constructor($$source: Partial<GenerateSSHKeyRequest> = {}) {
        if (!("algorithm" in $$source)) {
            this["algorithm"] = "";
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateSSHKeyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateSSHKeyRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateSSHKeyRequest($$parsedSource as Partial<GenerateSSHKeyRequest>);
    }
}

export class GeneratedSSHKey {
    "algorithm": string;
    "privateKey": string;
    "publicKey": string;
    "fingerprint": string;

    /** Creates a new GeneratedSSHKey instance. */
    constructor($$source: Partial<GeneratedSSHKey> = {}) {
        if (!("algorithm" in $$source)) {
            this["algorithm"] = "";
        }
        if (!("privateKey" in $$source)) {
            this["privateKey"] = "";
        }
        if (!("publicKey" in $$source)) {
            this["publicKey"] = "";
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneratedSSHKey instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneratedSSHKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneratedSSHKey($$parsedSource as Partial<GeneratedSSHKey>);
    }
}

export class Host {
    "id": string;
    "type": ItemType;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "password"?: string;
    "keyId"?: string;
    "identityId"?: string;
    "userpassIdentityIds"?: string[];
    "groupId"?: string;
    "relayHostId"?: string;
    "icon"?: string;
    "color"?: string;
    "startupCommand"?: string;
    "environment"?: { [_ in string]?: string };
    "terminalFontFamily"?: string;
    "terminalFontSize"?: number;

    /** Creates a new Host instance. */
    constructor($$source: Partial<Host> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     */
    static createFrom($$source: any = {}): Host {
        const $$createField9_0 = $$createType0;
        const $$createField15_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("userpassIdentityIds" in $$parsedSource) {
            $$parsedSource["userpassIdentityIds"] = $$createField9_0($$parsedSource["userpassIdentityIds"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField15_0($$parsedSource["environment"]);
        }
        return new Host($$parsedSource as Partial<Host>);
    }
}

export class HostGroup {
    "id": string;
    "type": ItemType;
    "name": string;
    "parentId"?: string;
    "sortOrder"?: number;
    "icon"?: string;
    "color"?: string;

    /** Creates a new HostGroup instance. */
    constructor($$source: Partial<HostGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): HostGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostGroup($$parsedSource as Partial<HostGroup>);
    }
}

export enum ItemType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeHost = "host",
    TypeKey = "key",
    TypeGroup = "group",
    TypeIdentity = "identity",
    TypeSnippet = "snippet",
};

export class SavedIdentity {
    "id": string;
    "type": ItemType;
    "name": string;
    "username": string;
    "password": string;

    /** Creates a new SavedIdentity instance. */
    constructor($$source: Partial<SavedIdentity> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedIdentity instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedIdentity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedIdentity($$parsedSource as Partial<SavedIdentity>);
    }
}

export class SavedKey {
    "id": string;
    "type": ItemType;
    "name": string;
    "privateKey": string;
    "publicKey"?: string;

    /** Creates a new SavedKey instance. */
    constructor($$source: Partial<SavedKey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("privateKey" in $$source)) {
            this["privateKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedKey instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedKey($$parsedSource as Partial<SavedKey>);
    }
}

export class SavedSnippet {
    "id": string;
    "type": ItemType;
    "name": string;
    "content": string;

    /** Creates a new SavedSnippet instance. */
    constructor($$source: Partial<SavedSnippet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedSnippet instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedSnippet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedSnippet($$parsedSource as Partial<SavedSnippet>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
