// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2181867912, id);
}

export function GetAll(): $CancellablePromise<$models.SavedSnippet[]> {
    return $Call.ByID(2179518132).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Save(snippet: $models.SavedSnippet): $CancellablePromise<string> {
    return $Call.ByID(1181333526, snippet);
}

// Private type creation functions
const $$createType0 = $models.SavedSnippet.createFrom;
const $$createType1 = $Create.Array($$createType0);
