// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(4040925645, id);
}

export function GetAll(): $CancellablePromise<$models.TabGroup[]> {
    return $Call.ByID(1146434829).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RemoveHostFromAllGroups drops every reference to a host from all tab groups.
 * Used when a host is deleted from the vault.
 */
export function RemoveHostFromAllGroups(hostID: string): $CancellablePromise<void> {
    return $Call.ByID(3440218955, hostID);
}

/**
 * RemoveHostInstance drops one host reference from a specific tab group.
 * Groups with no remaining hosts are deleted.
 */
export function RemoveHostInstance(groupID: string, hostID: string): $CancellablePromise<void> {
    return $Call.ByID(3815638683, groupID, hostID);
}

export function Save(group: $models.TabGroup): $CancellablePromise<string> {
    return $Call.ByID(2451892095, group);
}

// Private type creation functions
const $$createType0 = $models.TabGroup.createFrom;
const $$createType1 = $Create.Array($$createType0);
