// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Entry {
    "host": string;
    "port": number;
    "fingerprint": string;
    "keyType": string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }
        if (!("keyType" in $$source)) {
            this["keyType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

export class HostKeyCheck {
    "host": string;
    "port": number;
    "status": string;
    "fingerprint": string;
    "keyType": string;
    "storedFingerprint"?: string;

    /** Creates a new HostKeyCheck instance. */
    constructor($$source: Partial<HostKeyCheck> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }
        if (!("keyType" in $$source)) {
            this["keyType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostKeyCheck instance from a string or object.
     */
    static createFrom($$source: any = {}): HostKeyCheck {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostKeyCheck($$parsedSource as Partial<HostKeyCheck>);
    }
}
