// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckHost(host: string, port: number): $CancellablePromise<$models.HostKeyCheck> {
    return $Call.ByID(2497680179, host, port).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsTrusted(host: string, port: number, fingerprint: string): $CancellablePromise<boolean> {
    return $Call.ByID(1322855566, host, port, fingerprint);
}

export function List(): $CancellablePromise<$models.Entry[]> {
    return $Call.ByID(3769710047).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RemoveHost(host: string, port: number): $CancellablePromise<void> {
    return $Call.ByID(2731370981, host, port);
}

export function TrustHost(host: string, port: number, fingerprint: string, keyType: string): $CancellablePromise<void> {
    return $Call.ByID(3979671269, host, port, fingerprint, keyType);
}

// Private type creation functions
const $$createType0 = $models.HostKeyCheck.createFrom;
const $$createType1 = $models.Entry.createFrom;
const $$createType2 = $Create.Array($$createType1);
