// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LocalEntry {
    "name": string;
    "path": string;
    "size": number;
    "isDir": boolean;
    "modTime": number;

    /** Creates a new LocalEntry instance. */
    constructor($$source: Partial<LocalEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalEntry($$parsedSource as Partial<LocalEntry>);
    }
}
