// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function HomeDir(): $CancellablePromise<string> {
    return $Call.ByID(2160468745);
}

export function ListDir(dirPath: string): $CancellablePromise<$models.LocalEntry[]> {
    return $Call.ByID(3536058652, dirPath).then(($result: any) => {
        return $$createType1($result);
    });
}

export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(788934990, path);
}

export function RemovePath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3006857546, path);
}

// Private type creation functions
const $$createType0 = $models.LocalEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
